@url=http://localhost:3000
@auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OTZlMzQwYi1jYWJlLTQ3NjItOTcxYy00ZjM2YmFkNmUzN2QiLCJlbWFpbCI6Im11cmNob2lkQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaXNBY3RpdmUiOnRydWUsImlhdCI6MTc1MTU3NTkwNSwiZXhwIjoxNzUxNTc5NTA1fQ.C9V5ade0--cY6PMey5xGTAiI04FuP421kF8xb-RjslQ
@id=bcd1aad9-ebc7-4280-bdd9-c63bb3e97eff

### Seed fake data (clears and seeds all tables)
POST {{url}}/faker

### Create a user
POST {{url}}/users
Content-Type: application/json

{
  "name": "Michael Kamau",
  "email": "michael.kamau@example.com",
  "password": "securePassword123",
  "role": "DRIVER"
}

### Get all users
GET {{url}}/users
Authorization: Bearer {{auth}}

### Get a user by id
GET {{url}}/users/dbf0f12e-6fc8-43d4-94e0-e5954e6ead06

### Update a user
PATCH {{url}}/users/:id
Content-Type: application/json

{
  "name": "Jane Updated",
  "email": "jane.updated@example.com"
}

### Delete a user
DELETE {{url}}/users/dbf0f12e-6fc8-43d4-94e0-e5954e6ead06

### Create a driver
POST {{url}}/drivers
Content-Type: application/json
Authorization:  Bearer {{auth}}

{
  "userId": "3ad4ece7-c9c7-4928-8d8a-bbf6a1f6f7b1",
  "isAvailable": true,
  "baseLat": -1.2921,
  "baseLng": 36.8219
}

### Get all drivers
GET {{url}}/drivers
Authorization: Bearer {{auth}}

### Get a driver by id
GET {{url}}/drivers/:id

### Update a driver
PATCH {{url}}/drivers/:id
Content-Type: application/json

{
  "isAvailable": false,
  "baseLat": -1.3000,
  "baseLng": 36.8000
}

### Delete a driver
DELETE {{url}}/drivers/751c415f-8648-419e-a38a-c7891afcb922
### Create a vehicle
POST {{url}}/vehicles
Content-Type: application/json

{
  "model": "Toyota Prius",
  "plate": "KDA123A",
  "driverId": "REPLACE_WITH_DRIVER_ID"
}

### Get all vehicles
GET {{url}}/vehicles

### Get a vehicle by id
GET {{url}}/vehicles/:id

### Update a vehicle
PATCH {{url}}/vehicles/:id
Content-Type: application/json

{
  "model": "Toyota Corolla",
  "plate": "KDA999B"
}

### Delete a vehicle
DELETE {{url}}/vehicles/:id

### Create a booking
POST {{url}}/bookings
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "customerId": "496e340b-cabe-4762-971c-4f36bad6e37d",
  "pickupAddress": "123 Main St",
  "dropoffAddress": "456 Elm St",
  "pickupLat": 8.681495,
  "pickupLng": 49.41461,
  "dropoffLat": 49.41943,
  "dropoffLng": 8.686507,
  "distanceKm": null,
  "durationMins": null,
  "price": null,
  "stutus": "PENDING",
  "paymentStatus": "PENDING",
  "paymentMethod": "CASH"
}

### Get all bookings
GET {{url}}/bookings
Authorization: Bearer {{auth}}

### Get a booking by id
GET {{url}}/bookings/:id

### Update a booking locations
PATCH {{url}}/bookings/f78e839b-b665-4713-8384-d15f8d6dc3fa/locations
Content-Type: application/json

{
  "pickupLat": "49.41461",
  "pickupLng": "8.681495",
  "dropoffLat": "49.41943",
  "dropoffLng": "8.686507"
}


### Update a booking payment method
PATCH {{url}}/bookings/:id/payment-method
Content-Type: application/json

{
  "paymentMethod": "MPESA",
}


### Update a booking status
PATCH {{url}}/bookings/2c035293-0fe2-404d-84fb-12b285936a38/status
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "status": "COMPLETED"
}

### Update a booking pay ride
PATCH {{url}}/bookings/:id/pay-ride
Content-Type: application/json

{
  "paymentStatus": "PAID",
}


### AUTH ENDPOINTS

### Sign in
POST {{url}}/auths/signin
Content-Type: application/json

{
  "email": "murchoid@example.com",
  "password": "securePassword123"
}

### Sign out (replace :id with user id)
POST {{url}}/auths/signout/:id

### Refresh token (replace :id with user id, and use Bearer <refresh_token> in Authorization header)
POST {{url}}/auths/refresh-token?id=:id
Authorization: Bearer {{auth}}

### ANALYTICS ENDPOINTS

### Get analytics for current user (requires Authorization: Bearer <access_token>)
GET {{url}}/analytics/me
Authorization: Bearer {{auth}}

### Get admin analytics (requires Authorization: Bearer <access_token> for admin)
GET {{url}}/analytics/admin
Authorization: Bearer {{auth}}

###Make payment
POST {{url}}/payments
Content-Type: application/json

{
  "phoneNumber": "254799431541",
  "bookingId": "d3f4abd1-3e9c-4f28-ba89-c8669d941d0b"
}